version: '3'
services:
  web:
    build: .
    # command: uvicorn main:app --host '0.0.0.0' --port 3000 --reload
    ports:
      - "3000:3000"
    volumes:
      - ./src:/root/src
      - ./img:/root/img
      - ./api:/root/api
    environment: 
      - PORT=3000
    tty: true
