version: 2
 
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    # EC2 に SSH 接続・デプロイを実行
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
                fingerprints:
                    - "e3:b8:14:73:13:e0:c7:bc:c8:68:c3:d2:3b:5e:9e:40"
            # CircleCI に登録した環境変数を使って SSH
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /usr/share/nginx/html/auto-deploy-test && git pull'
 
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    # build ジョブに依存してるので、先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy
                filters:
                    branches:
                        only: master
